### PR TITLE
Add links to readme in documentation

### PR DESCRIPTION
**Pull request by TeaganKing**
Temporary fix for currently empty documentation

### CODE REVIEW

**Comment by TeaganKing** [comment]
@rmshkv this addresses the [currently empty installation instructions page](https://ncar.github.io/CUPiD/index.html) that you noticed!

**Review by rmshkv — APPROVED** [review]
This works! I also tried directly inputting the readme file in index.rst (`<../README.md>`) but that didn't seem to work at first - we may want to play around with that more later

**Comment by TeaganKing** [comment]
> This works! I also tried directly inputting the readme file in index.rst (`<../README.md>`) but that didn't seem to work at first - we may want to play around with that more later

Sounds good! I'll merge this now for a short-term solution, but it would be good to have the README fully linked there as you suggest so that we can update one and not have to update the other...

**Comment by TeaganKing** [comment]
(I am updating #38 to include Lev's suggestion)

**Pull request merged**
