### PR TITLE
Updated PR for seaice notebook.

### PR DESCRIPTION
**Pull request by dabail10**
### All Submissions:

* [X] Have you followed the guidelines in our [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide) (including the `pre-commit` check)?
* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [X] Does your submission pass tests?
2. [x] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] Have you successfully tested your changes locally?

I have made several updates to the sea ice notebook here.

1. Modified the cice_vars.yml file to have only three variables. I have created a new cice_vars_full.yml file for other use cases.
2. Changed the color tables from tab20 to ocean.
3. Added some Antarctic plots.
4. Added (in comments) a PBS DASK cluster option for running the notebook within jupyterhub.
5. Modified the cases in config.yml to be historical runs for seaice.
6. As an aside, I have also moved the timeseries files to ice/proc/tseries/month_1 for all of the cases instead of "ts".

### CODE REVIEW

**Comment by dabail10** [comment]
I apologize for all of the commit / push nonsense. I was trying to figure out the pre-commit stuff. I finally fixed it all!

**Comment by dabail10** [comment]
I guess I still need some help here with the PR Tasks.

**Comment by mnlevy1981** [comment]
Might be a little late now, but you can have `pre-commit` run these checks locally -- instructions are in the [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide)

**Comment by dabail10** [comment]
> Might be a little late now, but you can have `pre-commit` run these checks locally -- instructions are in the [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide)

I tried to install and run pre-commit, but I couldn't figure it out. Is it just pip install pre-commit? I did this and it still did not find the command.

**Comment by mnlevy1981** [comment]
> I guess I still need some help here with the PR Tasks.

That's meant to be a "pass if all the checklist items are complete, fail if something still needs to be done" but it isn't working quite right -- @TeaganKing is talking to the NCAR organization admin team to see about installing a better tool for that check. We can merge this in even if that check is failing, the `pre-commit` test is the important one

**Comment by mnlevy1981** [comment]
> > Might be a little late now, but you can have `pre-commit` run these checks locally -- instructions are in the [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide)
> 
> I tried to install and run pre-commit, but I couldn't figure it out. Is it just pip install pre-commit? I did this and it still did not find the command.

It should already be installed in `(cupid-dev)`, so try activating that environment and then running the `pre-commit` commands

**Comment by dabail10** [comment]
> > > Might be a little late now, but you can have `pre-commit` run these checks locally -- instructions are in the [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide)
> > 
> > 
> > I tried to install and run pre-commit, but I couldn't figure it out. Is it just pip install pre-commit? I did this and it still did not find the command.
> 
> It should already be installed in `(cupid-dev)`, so try activating that environment and then running the `pre-commit` commands

Ok. So, I had not updated the cupid-dev environment in many months. We should probably have something in the workflow about this if we don't already.

**Comment by TeaganKing** [comment]
> > I guess I still need some help here with the PR Tasks.
> 
> That's meant to be a "pass if all the checklist items are complete, fail if something still needs to be done" but it isn't working quite right -- @TeaganKing is talking to the NCAR organization admin team to see about installing a better tool for that check. We can merge this in even if that check is failing, the `pre-commit` test is the important one

See #139 -- this should be implemented shortly.

**Comment by dabail10** [comment]
I am waiting on this until the latest CUPiD is up to date.

**Pull request closed without merging**
