### PR TITLE
Cleanup PR #1

### PR DESCRIPTION
**Pull request by TeaganKing**
### Description of changes:
Address #151 by moving nblibrary out of examples and cleaning up the names of output directories. This PR also updates documentation to point to `key_metrics` example.

* [x] Have you followed the guidelines in our [Contributor's Guide](https://ncar.github.io/CUPiD/ContributorGuide.html)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you made sure that the [`pre-commit` checks passed (#8 in Adding Notebooks Guide)](https://ncar.github.io/CUPiD/addingnotebookstocollection.html)?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully tested your changes locally?

### CODE REVIEW

**Comment by TeaganKing** [comment]
Note: In addition to the items mentioned in the related issue, I am updating our documentation to use the `key_metrics` example instead of the `coupled_model` example.

**Comment by mnlevy1981** [comment]
> The `ADF` link in `external_diag_packages` seems to be working but the actual in-line plots are not showing up, so this needs to be further tested. Is this possibly related to the change @mnlevy1981 made in #154?

In the `external_diag_packages` directory, you'll need to modify`config.yml` so `adf_root` points to the right place:

```diff
- adf_root: ../../external_diag_packages/ADF/
+ adf_root: ../../externals/external_diag_packages/ADF/
```

`adf_root` is relative to where the notebook is run, which used to be `${CUPID_ROOT}/externals/nblibrary/atm` but is now `${CUPID_ROOT}/externals/nblibrary/atm`

**Comment by mnlevy1981** [comment]
> > The `ADF` link in `external_diag_packages` seems to be working but the actual in-line plots are not showing up, so this needs to be further tested. Is this possibly related to the change @mnlevy1981 made in #154?
> 
> In the `external_diag_packages` directory, you'll need to modify`config.yml` so `adf_root` points to the right place:
> 
> ```diff
> - adf_root: ../../external_diag_packages/ADF/
> + adf_root: ../../externals/external_diag_packages/ADF/
> ```
> 
> `adf_root` is relative to where the notebook is run, which used to be `${CUPID_ROOT}/externals/nblibrary/atm` but is now `${CUPID_ROOT}/nblibrary/atm`

Actually, you want 

```diff
- adf_root: ../../external_diag_packages/ADF/
+ adf_root: ../../externals/external_diag_packages/ADF_output/
```

(In #141 I changed the location of the ADF output in `build.py`, and I guess I never deleted `externals/external_diag_packages/ADF` so my testing didn't catch the change in `adf_root` until I started working on #154)

**Comment by TeaganKing** [comment]
I fixed the ADF path by setting the `adf_root` to `../../examples/external_diag_packages/ADF_output/`.

I'll work on the rof notebooks outside this PR.

This is ready for review.

**Review by mnlevy1981 — APPROVED** [review]
This looks great! I'm baffled by the ROF issue, especially because it looks like the notebook actually ran fine despite throwing a bunch of cryptic errors

**Comment by mnlevy1981** [comment]
FYI, it looks like we never added the runoff notebooks to the Jupyter Book... `config.yml` will need

```yaml
    - caption: River Runoff
      chapters:
        - file: rof/global_discharge_gauge_compare_obs
        - file: rof/global_discharge_ocean_compare_obs
```

Where the rest of the chapters are defined

**Comment by TeaganKing** [comment]
> FYI, it looks like we never added the runoff notebooks to the Jupyter Book... `config.yml` will need
> 
> ```yaml
>     - caption: River Runoff
>       chapters:
>         - file: rof/global_discharge_gauge_compare_obs
>         - file: rof/global_discharge_ocean_compare_obs
> ```
> 
> Where the rest of the chapters are defined

Ack, thanks for catching that! I remember looking at it so must have updated this in my own version somewhere... I'll follow up on that outside this PR.

**Pull request merged**
