### PR TITLE
Adding a new empty file

### PR DESCRIPTION
**Pull request by mnlevy1981**
Trying to test an update to the PR Tasks Completed Check action

### All Submissions:

* [x] Have you followed the guidelines in our Contributer's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide) (including the `pre-commit` check)?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by mnlevy1981** [comment]
I'm still seeing

```
GITHUB_TOKEN Permissions
  Checks: read
  Metadata: read
```

which doesn't seem right, given [`tasklist_completed.yml`](https://github.com/NCAR/CUPiD/actions/runs/9881359468/workflow?pr=114) contains

```yaml
    permissions:
      checks: write
```

I'll keep digging in, but we may want to consider the other tasklist checker action instead?

**Comment by mnlevy1981** [comment]
(for the record, I updated the permissions based on https://github.com/kentaro-m/task-completed-checker-action/issues/62 )

**Comment by TeaganKing** [comment]
Is it okay to close this PR, or did you want to do more testing with it @mnlevy1981 ?

**Comment by mnlevy1981** [comment]
Let's close this and revisit it later when we have a better idea of how to get a task list checker to work :)

**Pull request closed without merging**
