### PR TITLE
Config file documentation

### PR DESCRIPTION
**Pull request by TeaganKing**
This PR brings in additional documentation to describe our configuration file in order to clarify this setup information for CUPiD for users. This addresses #107.

* [x] Have you followed the guidelines in our [Contributor's Guide](https://github.com/NCAR/CUPiD/wiki/Contributor's-Guide) (including the `pre-commit` check)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you lint your code locally prior to submission?
* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully tested your changes locally?

We could also use the key metrics configuration file as an example if there is a preference for that.

### CODE REVIEW

**Review by mnlevy1981 — CHANGES_REQUESTED** [review]
For `config.md`, could we use the `config.yml` file from the `key_metrics` example instead of `coupled_model`? I haven't run the `coupled_model` example in a little while, and there's a chance the code captured in these screen shots no longer fits what CUPiD is expecting...

**Comment by TeaganKing** [comment]
Yes, I think that's a good idea. The images are rendering correctly now, but I'll update them to use the key metrics config file.
Screen Shot 2024-09-05 at 9 23 04 AM

**Comment by TeaganKing** [comment]
Here's updated screenshots using the key metrics configuration file.
Screen Shot 2024-09-05 at 9 39 09 AM
Screen Shot 2024-09-05 at 9 40 13 AM
Screen Shot 2024-09-05 at 9 40 19 AM

**Review by mnlevy1981 — APPROVED** [review]
These updates look great, sorry I didn't give this the 👍 last week :)

**Pull request merged**
